model:
  name: "oboe"
  params:
    p_type: "classification"
    runtime_limit: 90
    method: "TensorOboe"
    verbose: True
    # not from init
    metric: "roc_auc"

dataset:
  name: "census"
  params:
    load_path: "dataset_sources/census/adult.csv"
    input_type: "usual"
    train_test_split:
      test_size: 0.2

settings:
  dataset_name: "census"
  wandb:
    project: "census"
    tags:
      - "oboe"
      - "census"
  n_attempts: 10