model:
  name: "oboe"
  params:
    p_type: "classification"
    runtime_limit: 60
    method: "TensorOboe"
    verbose: True
    # not from init
    metric: "roc_auc"

dataset:
  name: "sepsis"
  params:
    load_path: "dataset_sources/sepsis/data.csv"
    input_type: "usual"
    train_test_split:
      test_size: 0.2

settings:
  dataset_name: ""
  wandb:
    project: "sepsis"
    tags:
      - "oboe"
      - "sepsis"
  n_attempts: 10