model:
  name: "auto-sklearn"
  params:
    time_left_for_this_task:
    metric: "roc_auc"
    scoring_functions:
       - "roc_auc"

dataset:
  name: ""
  params:
    load_path: ""
    input_type: "usual"
    train_test_split:
      test_size: 0.2

settings:
  dataset_name: ""
  wandb:
    project: ""
    tags:
      - "auto-sklearn"
      - ""
  n_attempts: 10