model:
  name: "catboost"
  params:
    - model
dataset:
  name: "diabetes"
  params:
    load_path: "dataset_sources/diabetes/data.csv"
    input_type: "usual"
    train_test_split:
      test_size: 0.2

settings:
  dataset_name: "diabetes"
  wandb:
    project: "diabetes"
    tags:
      - "catboost-optuna"
      - "30s"
  optuna_time_limit: 30
  catboost_time_limit: 2
  metric: "roc_auc"
  n_attempts: 10