model:
  name: "lama"
  params:
    task:
      name: "binary"
      metric: "auc"
    fit_predict_params:
      roles:
        target: "Diabetes_binary"
      verbose: 3

    gpu_ids: null
    memory_limit: 8
    cpu_limit: 4
    timeout: 30
    timing_params:
      overhead: 0
      mode: 2

dataset:
  name: "diabetes"
  params:
    load_path: "dataset_sources/diabetes/data.csv"
    input_type: "data_split"
    train_test_split:
      test_size: 0.2

settings:
  dataset_name: "diabetes"
  wandb:
    project: "diabetes"
    tags:
      - "lama"
      - "30s"
  n_attempts: 10