model:
  name: "lama"
  params:
    task:
      name: "binary"
      metric: "auc"
    fit_predict_params:
      roles:
        target: "Class"
      verbose: 3

    gpu_ids: null
    memory_limit: 8
    cpu_limit: 4
    timeout: 90
    timing_params:
      overhead: 0
      mode: 2

dataset:
  name: "fraud"
  params:
    load_path: "dataset_sources/fraud/creditcard_2023.csv"
    input_type: "data_split"
    train_test_split:
      test_size: 0.2

settings:
  wandb:
    project: "fraud"
    tags:
      - "lama"
      - "90s"
  n_attempts: 10